a = int(input('Vnesite prvo stevilo: '))
b = int(input('Vnesite drugo stevilo: '))
c = int(input('Vnesite tretje stevilo: '))
print('a =',a)
print(type(a))
print('b =',b)
print(type(b))
print('c =',c)
print(type(c))
print(b == a and c <= a)